questions = {
    "piec": "backen buk gebacken",
    "Zaczynac": "",
    "gryzc": "beisen biss gebissen",
    "oferowac": "bieten bot geboten",
    "giac": "biegen bog gebogen",
    "wiazac": "binden band gebunden",
    "prosic": "bitten bat gebaten",
    "zostawac": "bleiben blieb geblieben",
    "myslec": "denken dachte gedacht",
    "prosic": "bitten bat geboten",
    "polecac": "empfehlen empfahl empfohlen",
    "przestraszyc sie": "erschrecken erschrak erschrocken",
    "znajdowac": "finden fand gefunden",
    "zrec": "fressen fras gefressen",
    "obowiazywac": "gelten galt gegolten",
    "rozkoszowac sie": "geniesen genoss genossen",
    "wydarzyc sie": "geschehen geschah geschehen",
    "pozyczac": "leihen lieh geliehen",
    "czytac": "lesen las gelesen",
    "mierzyc": "messen mas gemessen",
    "wolac": "rufen rief gerufen",
    "podnosic sie": "steigen stieg gestiegen",
    "uderzac": "stosen stieg gestosen",
    "deptac": "treten trat getreten",
    "rosnac": "wachsen wuchs gewachsen",
    "rzucac": "werfen warf geworfen",
    "krzyczec": "schreien schrie geschrien",
    "plywac": "schwimmen shwamm geschwommen",
    "miec obowiazek": "sollen sollte gesollt",
    "blednac": "bleichen blich geblichen",
    "smazyc": "braten briet gebraten",
    "lamac": "brechen brach gebrochen",
    "przynosic": "bringen brachte gebracht",
    "jesc": "essen as gegessen",
    "jechac": "fahren fuhr gefahren",
    "upadac": "fallen fiel gefallen",
    "chwytac": "fangen find gefangen",
    "latac": "fliegen flog geflogen",
    "uciekac": "fliehen floh geflohen",
    "urodzic sie": "gebaren gebar geboren",
    "dawac": "geben gab gegeben",
    "isc": "gehen ging gegangen",
    "udac sie": "gelingen gelang gelungen",
    "wygrywac": "gewinnen gewann gewonnen",
    "podlewac": "giesen goss gegossen",
    "siegac": "griefen griff gegriffen",
    "miec": "haben hatte gehabt",
    "nazywac sie": "heisen hies geheisen",
    "pomagac": "helfen half geholfen",
    "znac": "kennen kannte gekannt",
    "pochodzic": "kommen kam gekommen",
    "podnosic": "heben hob gehoben",
    "moc": "konnen kann gekonnt",
    "ladowac": "laden lud geladen",
    "zostawiac": "lassen lies gelassen",
    "biegac": "laufen lief gelaufen",
    "lezec": "liegen lag gelegen",
    "klamac": "lugen log gelogen",
    "unikac": "meiden mied gemieden",
    "lubic": "mogen mochte gemocht",
    "musiec": "mussen musste gemusst",
    "brac": "nehmen nahm genommen",
    "nazywac": "nennen nannte genannt",
    "radzic": "raten riet geraten",
    "jezdzic konno": "reiten ritt geritten",
    "pedzic (s)": "rennen rennte gerannt",
    "pachniec": "riechen roch gerochen",
    "rozstac sie": "scheiden schied geschieden",
    "mowic": "sprechen sprach gesprochen",
    "skakac": "springen sprang gesprungen",
    "kluc": "stechen stach gestochen",
    "stac": "stehen stand gestanden",
    "krasc": "stehlen stahl gestohlen",
    "umierac": "sterben starb gestorben",
    "skreslac": "streichen strich gestrichen",
    "klocic sie": "streiten stritt gestritten",
    "nosic": "tragen trug getragen",
    "spotykac sie": "treffen traf getroffen",
    "pedzic (h)": "treiben trieb getrieben",
    "pic": "trinken trank getrunken",
    "czynic": "tun tat getan",
    "zapominac": "vergessen vergas vergessen",
    "zgubic": "verlieren verlor verloren",
    "znikac": "verschwinden verschwand verschwunden",
    "trzymac": "halten hielt gehalten",
    "myc": "waschen wusch gewaschen",
    "reklamowac": "werben warb geworben",
    "stawac sie": "werden wurde geworden",
    "wiedziec": "wissen wusste gewusst",
    "ciagnac": "ziehen zog gezogen",
    "zmuszac": "zwingen zwang gezwungen",
    "swiecic": "scheinen schien geschienen",
    "pchac": "schieben schob geschoben",
    "strzelac": "schiesen schoss geschossen",
    "spac": "schlafen schlief geschlafen",
    "bic": "schlagen schlug geschlagen",
    "zamykac": "schlies schloss geschlossen",
    "kroic": "schneiden schnitt geschnitten",
    "pisac": "schreiben schrieb seschrieben",
    "milczec": "schweigen schwieg geschwiegen",
    "puchnac": "schwellen schwoll geschwollen",
    "widziec": "sehen sah gesehen",
    "byc": "sein war gewesen",
    "spiewac": "singen sang gesungen",
    "siedziec": "sitzen sas geseseen"
}